name: Sync Upstream

# This runs every day on 1801 UTC
on:
  schedule:
    - cron: '1 18 * * *'
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: GitHub Sync to Upstream Repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with: 
          upstream_repo: "https://github.com/jsmsj/GdriveCloneBot.git"
          upstream_branch: "master"
          downstream_branch: "master"
          token: ${{ secrets.GITHUB_TOKEN }}
          