name: Railway Deploy

on:
  push:
    branches: railway-deploy


jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/railway-deploy' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Railway Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          bot_token: ${{ secrets.bot_token }}
          allowed_user_ids: ${{ secrets.allowed_user_ids }}
          db_url: ${{ secrets.db_url }}
          G_DRIVE_CLIENT_ID: ${{ secrets.G_DRIVE_CLIENT_ID }}
          G_DRIVE_CLIENT_SECRET : ${{ secrets.G_DRIVE_CLIENT_SECRET }}
          prefix : ${{ secrets.prefix }}